# --- CONEXIÓN A MYSQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/nexus_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# El driver que acabamos de instalar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- COMPORTAMIENTO DE HIBERNATE ---
# 'update': Crea las tablas si no existen, pero NO borra los datos viejos al reiniciar.
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la terminal (opcional, sirve para ver qué hace)
spring.jpa.show-sql=true